apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test-deployment
  labels:
    app: k8-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8-test
  template:
    metadata:
      labels:
        app: k8-test
    spec:
      containers:
      - name: static-site
        image: thenetworkchuck/nccoffee:pourover #or vacpot
        imagePullPolicy: Always
        ports:
        - containerPort: 80
